export const TEAM_DEFAULT_DEPARTMENTS = [
  ['strategy', 'Strategy', 'Strategic planning and positioning'],
  ['creative', 'Creative', 'Creative direction and ideation'],
  ['design', 'Design', 'Visual design and brand assets'],
  ['social-media', 'Social Media', 'Social media management'],
  ['paid-media', 'Paid Media', 'Paid traffic and acquisition'],
  ['copywriting', 'Copywriting', 'Copy and conversion writing'],
  ['content', 'Content', 'Content production'],
  ['web-development', 'Web / Development', 'Websites, landing pages and systems'],
  ['client-success', 'Client Success', 'Client relationship and retention'],
  ['sales', 'Sales', 'Commercial and pipeline management'],
  ['finance', 'Finance', 'Finance and profitability'],
  ['operations', 'Operations', 'Operational management'],
  ['administration', 'Administration', 'Administrative routines'],
] as const;

export const TEAM_DEFAULT_SKILLS = [
  ['marketing-strategy', 'Marketing Strategy', 'Strategy'],
  ['brand-strategy', 'Brand Strategy', 'Strategy'],
  ['social-media-management', 'Social Media Management', 'Content'],
  ['copywriting', 'Copywriting', 'Content'],
  ['paid-traffic', 'Paid Traffic', 'Paid Media'],
  ['meta-ads', 'Meta Ads', 'Paid Media'],
  ['google-ads', 'Google Ads', 'Paid Media'],
  ['seo', 'SEO', 'Development'],
  ['landing-pages', 'Landing Pages', 'Development'],
  ['web-design', 'Web Design', 'Design'],
  ['video-editing', 'Video Editing', 'Design'],
  ['motion-design', 'Motion Design', 'Design'],
  ['crm', 'CRM', 'Sales'],
  ['automation', 'Automation', 'AI / Automation'],
  ['client-management', 'Client Management', 'Client Success'],
  ['project-management', 'Project Management', 'Operations'],
  ['financial-management', 'Financial Management', 'Finance'],
  ['data-analysis', 'Data Analysis', 'Operations'],
  ['ai-prompting', 'AI Prompting', 'AI / Automation'],
  ['reporting', 'Reporting', 'Operations'],
] as const;
