import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Records which policy, at which version, produced each recommendation (R2.1).
 *
 * Before this, the thresholds behind a stored recommendation were readable only
 * from the TypeScript constant in force at the time it was *displayed*. Lower
 * `minimumFailureRate` next quarter and every historical row silently starts
 * claiming it crossed a limit that did not exist when it was generated — an
 * audit record of a production change whose justification rewrites itself.
 *
 * Three additive columns, no data touched:
 *
 * - `policy_key` — stable identity (`automation_failure_pause`), without the
 *   version suffix the old key carried, so every recommendation a policy ever
 *   made is findable with an equality rather than a LIKE.
 * - `policy_version` — integer revision. A rules change is a new version, never
 *   an edit to a published one.
 * - `policy_snapshot` — the effective parameters, frozen at generation.
 *
 * ## Why the two identity columns are nullable
 *
 * Production currently holds no recommendations, but the schema must not be
 * designed on that assumption: any other environment that ran the previous code
 * may hold rows, and this migration has to be correct for them. A NOT NULL
 * column would force a backfilled value, and the only value available would be
 * the current policy's — which would assert that a pre-R2.1 row used v1's
 * thresholds. That is a claim this migration cannot honestly make: those rows
 * were generated by code that did not record what it applied. Null says
 * "unknown", which is the truth, and it is distinguishable from v1 by a reader.
 *
 * `policy_snapshot` defaults to `'{}'` instead, because "no parameters
 * recorded" is unambiguous for a JSONB bag and spares every read a null check.
 *
 * Nothing in the recommendation lifecycle changes: no status, no config, no
 * decision, no version row, and no LeadFlow operational table is touched.
 */
export class AddIntelligenceRecommendationPolicyIdentity1791400000000 implements MigrationInterface {
  name = 'AddIntelligenceRecommendationPolicyIdentity1791400000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "leadflow_intelligence_recommendations"
        ADD COLUMN IF NOT EXISTS "policy_key" varchar(80),
        ADD COLUMN IF NOT EXISTS "policy_version" integer,
        ADD COLUMN IF NOT EXISTS "policy_snapshot" jsonb NOT NULL DEFAULT '{}'::jsonb
    `);

    // Finds "everything this policy ever decided" and "everything decided under
    // the rules that changed", which are the two questions the columns exist to
    // answer. Partial, because pre-R2.1 rows have nothing to index.
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_lf_intelligence_recommendations_policy"
        ON "leadflow_intelligence_recommendations" ("policy_key", "policy_version")
        WHERE "policy_key" IS NOT NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP INDEX IF EXISTS "IDX_lf_intelligence_recommendations_policy"
    `);
    await queryRunner.query(`
      ALTER TABLE "leadflow_intelligence_recommendations"
        DROP COLUMN IF EXISTS "policy_snapshot",
        DROP COLUMN IF EXISTS "policy_version",
        DROP COLUMN IF EXISTS "policy_key"
    `);
  }
}
