import { AddIntelligenceRecommendationPolicyIdentity1791400000000 } from './1791400000000-add-intelligence-recommendation-policy-identity';

/**
 * R2.1: three additive columns on one table.
 *
 * The migration's whole claim is that it is narrow and safe with existing rows,
 * so the spec asserts exactly that: nothing dropped, nothing renamed, no
 * operational table touched, and no NOT NULL on the identity columns that would
 * force a fabricated value onto rows generated before the platform recorded it.
 */
describe('AddIntelligenceRecommendationPolicyIdentity1791400000000 migration', () => {
  const run = async (direction: 'up' | 'down') => {
    const sql: string[] = [];
    const queryRunner = {
      query: jest.fn((statement: string) => {
        sql.push(statement);
        return Promise.resolve();
      }),
    };

    await new AddIntelligenceRecommendationPolicyIdentity1791400000000()[
      direction
    ](queryRunner as never);

    return sql.join('\n');
  };

  it('adds the three policy columns to the recommendations table', async () => {
    const joined = await run('up');

    expect(joined).toContain('leadflow_intelligence_recommendations');
    expect(joined).toContain('ADD COLUMN IF NOT EXISTS "policy_key"');
    expect(joined).toContain('ADD COLUMN IF NOT EXISTS "policy_version"');
    expect(joined).toContain('ADD COLUMN IF NOT EXISTS "policy_snapshot"');
  });

  /**
   * The identity columns must stay nullable. A NOT NULL would demand a
   * backfilled value for pre-R2.1 rows, and the only value available is the
   * current policy's — which would assert those rows used v1's thresholds. They
   * were generated by code that did not record what it applied; null says so.
   */
  it('leaves the identity columns nullable so historical rows stay honest', async () => {
    const joined = await run('up');

    expect(joined).toMatch(/"policy_key" varchar\(80\)\s*,/);
    expect(joined).toMatch(/"policy_version" integer\s*,/);
    expect(joined).not.toContain('"policy_key" varchar(80) NOT NULL');
    expect(joined).not.toContain('"policy_version" integer NOT NULL');
  });

  /** A JSONB bag has an unambiguous empty value, so this one gets a default. */
  it('defaults the snapshot to an empty object', async () => {
    const joined = await run('up');

    expect(joined).toContain(
      `"policy_snapshot" jsonb NOT NULL DEFAULT '{}'::jsonb`,
    );
  });

  it('is purely additive and touches no other table', async () => {
    const joined = await run('up');

    expect(joined).not.toContain('DROP COLUMN');
    expect(joined).not.toContain('DROP TABLE');
    expect(joined).not.toContain('TRUNCATE');
    expect(joined).not.toContain('DELETE');
    expect(joined).not.toContain('UPDATE ');
    expect(joined).not.toContain('RENAME');

    for (const untouched of [
      'leadflow_automations',
      'leadflow_automation_runs',
      'leadflow_intelligence_decisions',
      'leadflow_intelligence_config_versions',
      'leadflow_intelligence_results',
      'platform_permissions',
    ]) {
      expect(joined).not.toContain(untouched);
    }
  });

  /** Nothing changes about status, config, or any lifecycle column. */
  it('does not touch the recommendation lifecycle', async () => {
    const joined = await run('up');

    for (const untouched of [
      'status',
      'current_config',
      'proposed_config',
      'applied_at',
      'rolled_back_at',
      'confidence',
      'evidence',
      'segment',
      'baseline',
      'generation_key',
      'business_mode_key',
    ]) {
      expect(joined).not.toContain(`"${untouched}"`);
    }
  });

  it('indexes the identity for policy-scoped queries', async () => {
    const joined = await run('up');

    expect(joined).toContain(
      'CREATE INDEX IF NOT EXISTS "IDX_lf_intelligence_recommendations_policy"',
    );
    expect(joined).toContain('("policy_key", "policy_version")');
    // Partial: pre-R2.1 rows have nothing to index.
    expect(joined).toContain('WHERE "policy_key" IS NOT NULL');
  });

  it('is reversible', async () => {
    const joined = await run('down');

    expect(joined).toContain(
      'DROP INDEX IF EXISTS "IDX_lf_intelligence_recommendations_policy"',
    );
    expect(joined).toContain('DROP COLUMN IF EXISTS "policy_key"');
    expect(joined).toContain('DROP COLUMN IF EXISTS "policy_version"');
    expect(joined).toContain('DROP COLUMN IF EXISTS "policy_snapshot"');
  });
});
